//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspSite.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public int author_id { get; set; }
        public string name { get; set; }
        public string about { get; set; }
        public int picture_id { get; set; }
    
        public virtual Picture Picture { get; set; }
    }
}
